"use client";

import { cn } from "@/lib/utils";

export interface BingoCardCustomization {
  cellBackgroundColor: string;
  cellTextColor: string;
  cellBorderColor: string;
  freeCellBackgroundColor: string;
  freeCellTextColor: string;
  titleColor: string;
  footerColor: string;
  cardBackgroundColor: string;
}

interface BingoCardProps {
  items: string[];
  customization?: Partial<BingoCardCustomization>;
}

export function BingoCard({ items, customization }: BingoCardProps) {
  // Default customization values
  const defaults: BingoCardCustomization = {
    cellBackgroundColor: "#ffffff",
    cellTextColor: "#111827",
    cellBorderColor: "#1f2937",
    freeCellBackgroundColor: "#fbbf24",
    freeCellTextColor: "#ffffff",
    titleColor: "#111827",
    footerColor: "#6b7280",
    cardBackgroundColor: "transparent",
  };

  const custom = { ...defaults, ...customization };

  // Calculate font size based on text length - smaller on mobile
  const getFontSize = (text: string) => {
    const length = text.length;
    if (length <= 20) return "text-[0.45rem] sm:text-[0.6rem]";
    if (length <= 35) return "text-[0.4rem] sm:text-[0.55rem]";
    if (length <= 50) return "text-[0.35rem] sm:text-[0.5rem]";
    return "text-[0.3rem] sm:text-[0.45rem]";
  };

  return (
    <div
      className="print-card"
      style={{ backgroundColor: custom.cardBackgroundColor }}
    >
      <div className="mb-4 text-center">
        <h2
          className="text-2xl sm:text-3xl font-bold mb-2 tracking-wider"
          style={{
            fontFamily: "Georgia, 'Times New Roman', serif",
            letterSpacing: "0.15em",
            color: custom.titleColor,
          }}
        >
          2026 BINGO
        </h2>
      </div>
      <div className="grid grid-cols-5 gap-1.5 sm:gap-2 max-w-md mx-auto">
        {items.map((item, index) => (
          <div
            key={index}
            className={cn(
              "aspect-square border-2 sm:border-[3px] rounded-md sm:rounded-lg",
              "flex items-center justify-center text-center font-medium transition-all",
              "overflow-hidden",
              index === 12 ? "shadow-lg p-0" : "p-1.5 sm:p-2"
            )}
            style={{
              backgroundColor:
                index === 12
                  ? custom.freeCellBackgroundColor
                  : custom.cellBackgroundColor,
              borderColor: custom.cellBorderColor,
            }}
          >
            {index === 12 ? (
              <span
                className="text-xl sm:text-2xl font-bold w-full h-full flex items-center justify-center"
                style={{ color: custom.freeCellTextColor }}
              >
                {item}
              </span>
            ) : (
              <span
                className={cn(
                  "break-words leading-[1.25] w-full",
                  "px-0.5",
                  getFontSize(item)
                )}
                style={{ color: custom.cellTextColor }}
              >
                {item}
              </span>
            )}
          </div>
        ))}
      </div>
      <div
        className="mt-4 text-center text-xs sm:text-sm"
        style={{ color: custom.footerColor }}
      >
        <p>Generated by Together, Not For</p>
      </div>
    </div>
  );
}
