"use client";

import { cn } from "@/lib/utils";

export interface BingoCardCustomization {
  cellBackgroundColor: string;
  cellTextColor: string;
  cellBorderColor: string;
  freeCellBackgroundColor: string;
  freeCellTextColor: string;
  titleColor: string;
  footerColor: string;
  cardBackgroundColor: string;
  cellFontSize: number; // Font size multiplier (0.5 to 2.0)
  cellBorderSize: number; // Border size in pixels (1 to 8)
}

interface BingoCardProps {
  items: string[];
  customization?: Partial<BingoCardCustomization>;
}

export function BingoCard({ items, customization }: BingoCardProps) {
  // Default customization values
  const defaults: BingoCardCustomization = {
    cellBackgroundColor: "#ffffff",
    cellTextColor: "#111827",
    cellBorderColor: "#1f2937",
    freeCellBackgroundColor: "#fbbf24",
    freeCellTextColor: "#ffffff",
    titleColor: "#111827",
    footerColor: "#6b7280",
    cardBackgroundColor: "transparent",
    cellFontSize: 1.0,
    cellBorderSize: 3,
  };

  const custom = { ...defaults, ...customization };

  // Calculate font size based on text length and user's font size multiplier
  const getFontSize = (text: string, isMobile: boolean = false) => {
    const baseSize = custom.cellFontSize || 1.0;
    const length = text.length;
    let baseFontSize = 0.6; // Base size in rem

    if (length <= 20) baseFontSize = 0.6;
    else if (length <= 35) baseFontSize = 0.55;
    else if (length <= 50) baseFontSize = 0.5;
    else baseFontSize = 0.45;

    const adjustedSize = baseFontSize * baseSize;
    // Mobile is 75% of desktop size
    return isMobile ? `${adjustedSize * 0.75}rem` : `${adjustedSize}rem`;
  };

  return (
    <div
      className="print-card"
      style={{ backgroundColor: custom.cardBackgroundColor }}
    >
      <div className="mb-4 text-center">
        <h2
          className="text-2xl sm:text-3xl font-bold mb-2 tracking-wider"
          style={{
            fontFamily: "Georgia, 'Times New Roman', serif",
            letterSpacing: "0.15em",
            color: custom.titleColor,
          }}
        >
          2026 BINGO
        </h2>
      </div>
      <div className="grid grid-cols-5 gap-1.5 sm:gap-2 max-w-md mx-auto">
        {items.map((item, index) => {
          const borderSize = custom.cellBorderSize || 3;
          return (
            <div
              key={index}
              className={cn(
                "aspect-square rounded-md sm:rounded-lg",
                "flex items-center justify-center text-center font-medium transition-all",
                "overflow-hidden",
                index === 12 ? "shadow-lg p-0" : "p-1.5 sm:p-2"
              )}
              style={{
                backgroundColor:
                  index === 12
                    ? custom.freeCellBackgroundColor
                    : custom.cellBackgroundColor,
                borderColor: custom.cellBorderColor,
                borderWidth: `${borderSize}px`,
                borderStyle: "solid",
              }}
            >
              {index === 12 ? (
                <span
                  className="font-bold w-full h-full flex items-center justify-center text-[1rem] sm:text-[1.25rem]"
                  style={{
                    color: custom.freeCellTextColor,
                    whiteSpace: "nowrap",
                  }}
                >
                  {item}
                </span>
              ) : (
                <span
                  className={cn("leading-[1.25] w-full", "px-0.5")}
                  style={{
                    color: custom.cellTextColor,
                    fontSize: getFontSize(item, false),
                    wordBreak: "normal",
                    overflowWrap: "normal",
                    hyphens: "none",
                  }}
                >
                  {item}
                </span>
              )}
            </div>
          );
        })}
      </div>
      <div
        className="mt-4 text-center text-xs sm:text-sm"
        style={{ color: custom.footerColor }}
      >
        <p>Generated by Together, Not For</p>
      </div>
    </div>
  );
}
