export type Theme =
  | "basic"
  | "goals"
  | "regrets"
  | "ideas"
  | "innovations"
  | "hobbies"
  | "mindset"
  | "spicy"
  | "spicy2"
  | "spicy3"
  | "travel"
  | "fitness"
  | "creativity";

export const THEMED_ITEMS: Record<Theme, string[]> = {
  basic: [
    "Started a new hobby (and stuck with it 30 days)",
    'Deleted an app you "couldn\'t live without"',
    "Took a social media break for a week",
    "Read a book you actually finished",
    "Joined a club or recurring group",
    "Hosted a dinner or potluck",
    "Went to a museum or gallery",
    "Tried a new cuisine you'd never ordered before",
    "Learned a new recipe you'll reuse",
    "Cooked a meal entirely from pantry staples",
    "Packed lunch instead of buying it (5 times)",
    "Tried meal prep (even a lazy version)",
    "Made coffee at home for a month",
    'Did a "no spend" weekend',
    "Negotiated a bill or subscription",
    "Canceled a subscription you forgot about",
    "Hit a savings milestone (any size)",
    "Checked your credit report",
    "Updated your budget categories",
    'Sold something you\'ve been "meaning to list"',
    "Donated a box of stuff",
    "Decluttered one doom drawer",
    "Cleaned behind the fridge/stove (yes, really)",
    "Finally fixed the small annoying thing at home",
    "Changed an air filter",
    "Organized your cables / charging station",
    "Backed up your photos",
    "Cleaned up your email inbox (1,000+ gone)",
    "Unsubscribed from 25 email lists",
    "Went to bed before 10:30 for a week",
    "Took a proper sick day (rested, no guilt)",
    "Got a physical / annual checkup",
    "Scheduled the appointment you've avoided",
    "Walked 10k steps in a day",
    'Did a "stretching only" workout day',
    "Completed a 30-minute workout",
    "Tried yoga or mobility class",
    "Tried a new sport or activity",
    "Went hiking or to a nature trail",
    "Watched a sunrise",
    "Watched a sunset",
    "Took a day trip to a nearby town",
    "Booked a weekend getaway",
    "Traveled somewhere new (even one county over)",
    "Took a spontaneous drive with no destination",
    "Went to a farmers market",
    "Ate outside just because",
    "Took yourself on a solo date",
    "Went to a concert/show/comedy night",
    "Saw live music at a bar/park",
    "Went to a local festival",
    "Did karaoke",
    "Danced in public",
    "Started a conversation with a stranger",
    "Gave a genuine compliment to someone",
    "Wrote a thank-you note (handwritten)",
    "Reconnected with an old friend",
    "Made a new friend",
    "Set a boundary and kept it",
    'Said "no" without over-explaining',
    "Asked for help when you needed it",
    "Did something alone you usually wait for others to do",
    "Tried therapy/coaching/journaling regularly",
    "Journaled 7 days in a row",
    'Did a "brain dump" and made a plan',
    "Kept a promise to yourself",
    "Started a habit tracker",
    "Finished a project you've postponed",
    "Launched something (post, site, product, side project)",
    'Shipped a "v1" instead of perfecting forever',
    "Learned a new tool (spreadsheets, design, code, etc.)",
    "Automated something annoying in your life",
    "Cleaned up your desktop / file system",
    "Updated your passwords / enabled MFA",
    "Replaced something worn-out you keep tolerating",
    "Got rid of clothes that don't fit your life anymore",
    "Tried a new haircut or style",
    "Changed up your routine (new route, new gym time, etc.)",
    "Took a cold plunge / cold shower",
    "Did a sauna / steam room session",
    "Took a nap without setting an alarm",
    'Had a full "phone-free" morning',
    'Had a full "phone-free" evening',
    "Went a day without complaining",
    "Meditated for 10 minutes",
    "Took vitamins consistently for a month",
    "Drank enough water for 7 straight days",
    "Tried a mocktail night instead of drinking",
    "Went on a date night (planned)",
    "Went on a date night (spontaneous)",
    "Initiated intimacy you actually wanted",
    'Bought yourself flowers / a small treat "just because"',
    "Had a meaningful talk without distractions",
    'Made a "joy list" and did one thing from it',
    "Did a random act of kindness",
    "Volunteered for an hour",
    "Left a thoughtful review for a small business",
    'Asked someone "how can I support you this week?"',
    "Tried something that scared you a little (but was safe)",
    "Forgave yourself for something you've been carrying",
  ],
  goals: [
    "Run a 5K race",
    "Save $5,000 this year",
    "Read 24 books",
    "Learn a new language",
    "Get a promotion",
    "Start a side business",
    "Buy a house",
    "Travel to 3 new countries",
    "Complete a certification",
    "Run a marathon",
    "Write a book",
    "Start investing",
    "Get in the best shape of my life",
    "Master a new skill",
    "Build an emergency fund",
    "Start a YouTube channel",
    "Learn to play an instrument",
    "Complete a home renovation",
    "Start a garden",
    "Volunteer 100 hours",
    "Get a degree or certification",
    "Start a retirement fund",
    "Learn to cook 10 new dishes",
    "Complete a fitness challenge",
    "Start a blog",
    "Learn photography",
    "Get a new job",
    "Pay off all debt",
    "Start a podcast",
    "Learn to code",
    "Take a solo trip",
    "Start a daily meditation practice",
    "Complete a 30-day challenge",
    "Learn public speaking",
    "Start a book club",
    "Get a professional certification",
    "Start a savings goal tracker",
    "Learn graphic design",
    "Start a morning routine",
    "Complete a personal project",
  ],
  regrets: [
    "Didn't take that job opportunity",
    "Didn't travel when I had the chance",
    "Didn't call my parents more",
    "Didn't pursue that passion",
    "Didn't save money earlier",
    "Didn't take care of my health",
    "Didn't end that toxic relationship sooner",
    "Didn't learn that skill I wanted",
    "Didn't start that business idea",
    "Didn't say 'I love you' more often",
    "Didn't take more risks",
    "Didn't spend time with friends",
    "Didn't pursue higher education",
    "Didn't invest in myself",
    "Didn't travel solo",
    "Didn't learn to cook",
    "Didn't exercise regularly",
    "Didn't save for retirement",
    "Didn't take that class",
    "Didn't start that hobby",
    "Didn't network more",
    "Didn't ask for help",
    "Didn't set boundaries",
    "Didn't prioritize mental health",
    "Didn't learn financial literacy",
    "Didn't take breaks",
    "Didn't celebrate small wins",
    "Didn't document memories",
    "Didn't try new things",
    "Didn't be more present",
    "Didn't forgive sooner",
    "Didn't express gratitude",
    "Didn't take photos",
    "Didn't write in a journal",
    "Didn't learn from failures",
    "Didn't take that trip",
    "Didn't call that friend",
    "Didn't say yes to opportunities",
    "Didn't say no to things I didn't want",
    "Didn't trust my instincts",
  ],
  ideas: [
    "Start a community garden",
    "Create a local book exchange",
    "Organize neighborhood cleanups",
    "Start a skill-sharing group",
    "Create a meal prep service",
    "Start a walking group",
    "Organize a local market",
    "Create a mentorship program",
    "Start a repair cafe",
    "Organize a swap meet",
    "Create a time bank",
    "Start a tool library",
    "Organize a community event",
    "Create a local newsletter",
    "Start a makerspace",
    "Organize a study group",
    "Create a recipe exchange",
    "Start a carpool system",
    "Organize a clothing swap",
    "Create a local directory",
    "Start a podcast about local issues",
    "Organize a film screening",
    "Create a community art project",
    "Start a local history project",
    "Organize a talent show",
    "Create a neighborhood app",
    "Start a community kitchen",
    "Organize a game night",
    "Create a local guide",
    "Start a support group",
    "Organize a workshop series",
    "Create a resource library",
    "Start a community board",
    "Organize a festival",
    "Create a local blog",
    "Start a volunteer network",
    "Organize a fundraiser",
    "Create a mentorship matching",
    "Start a discussion group",
    "Organize a cultural exchange",
  ],
  innovations: [
    "AI-powered personal assistant",
    "Sustainable packaging solution",
    "Smart home automation system",
    "Renewable energy device",
    "Health monitoring wearable",
    "Educational app for kids",
    "Food waste reduction app",
    "Virtual reality training tool",
    "Blockchain voting system",
    "3D printing service platform",
    "Electric vehicle charging network",
    "Water purification device",
    "Mental health app",
    "Remote work collaboration tool",
    "Sustainable fashion platform",
    "Personal finance AI",
    "Language learning VR",
    "Smart agriculture system",
    "Accessibility tech solution",
    "Carbon footprint tracker",
    "Telemedicine platform",
    "Smart city infrastructure",
    "Recycling innovation",
    "Biometric security system",
    "Augmented reality shopping",
    "Personalized learning platform",
    "Smart transportation app",
    "Energy-efficient appliance",
    "Digital wellness tool",
    "Automated farming system",
    "Voice-controlled interface",
    "Gesture recognition tech",
    "Smart grid solution",
    "Biodegradable material",
    "Personalized medicine tool",
    "Automated delivery system",
    "Smart waste management",
    "Virtual event platform",
    "AI content creation tool",
    "Sustainable building material",
  ],
  hobbies: [
    "Photography",
    "Painting",
    "Drawing",
    "Sculpting",
    "Pottery",
    "Knitting",
    "Crocheting",
    "Sewing",
    "Woodworking",
    "Gardening",
    "Cooking",
    "Baking",
    "Reading",
    "Writing",
    "Journaling",
    "Calligraphy",
    "Origami",
    "Scrapbooking",
    "Collecting stamps",
    "Collecting coins",
    "Bird watching",
    "Hiking",
    "Camping",
    "Fishing",
    "Cycling",
    "Running",
    "Swimming",
    "Yoga",
    "Dancing",
    "Playing guitar",
    "Playing piano",
    "Singing",
    "Learning languages",
    "Chess",
    "Board games",
    "Video games",
    "Puzzles",
    "Sudoku",
    "Crosswords",
    "Model building",
    "RC cars/planes",
    "Astronomy",
    "Stargazing",
    "Geocaching",
    "Rock climbing",
    "Surfing",
    "Kayaking",
    "Skiing",
    "Snowboarding",
    "Martial arts",
    "Archery",
  ],
  mindset: [
    "Practice gratitude daily",
    "Embrace failure as learning",
    "Focus on progress not perfection",
    "Practice mindfulness",
    "Challenge negative thoughts",
    "Set boundaries",
    "Practice self-compassion",
    "Embrace uncertainty",
    "Focus on what I can control",
    "Practice patience",
    "Cultivate curiosity",
    "Embrace change",
    "Practice resilience",
    "Focus on solutions not problems",
    "Practice active listening",
    "Embrace vulnerability",
    "Practice forgiveness",
    "Focus on the present moment",
    "Practice acceptance",
    "Embrace imperfection",
    "Practice empathy",
    "Focus on growth mindset",
    "Practice self-reflection",
    "Embrace discomfort",
    "Practice intentional living",
    "Focus on values not validation",
    "Practice letting go",
    "Embrace new perspectives",
    "Practice balance",
    "Focus on process not outcome",
    "Practice authenticity",
    "Embrace the journey",
    "Practice kindness to self",
    "Focus on abundance mindset",
    "Practice emotional regulation",
    "Embrace challenges",
    "Practice positive self-talk",
    "Focus on learning mindset",
    "Practice being present",
    "Embrace uncertainty with courage",
  ],
  spicy: [
    "Tried a new sex position",
    "Had sex in a new location at home",
    "Had shower sex",
    "Had sex in front of a mirror",
    "Had morning sex",
    "Had a quickie",
    "Had a slow, drawn-out session",
    "Went down on your partner",
    "Got oral sex",
    "Swallowed",
    "Finished on your partner",
    "Came at the same time",
    "Had sex multiple times in one day",
    "Used a vibrator during sex",
    "Used a new sex toy together",
    "Tried dirty talk",
    "Sent a nude",
    "Received a nude",
    "Sexted a full scenario",
    "Watched adult content together",
    "Read erotica together",
    "Tried roleplay",
    "Tried light domination with commands",
    "Tried being more vocal on purpose",
    "Tried hands pinned above your head",
    "Tried being held down",
    "Tried spanking",
    "Tried hair pulling",
    "Tried face sitting",
    "Tried deep throat",
    "Had sex with a fantasy you both agreed on",
    "Tried edging",
    "Tried orgasm control",
    "Tried a new lubricant",
    "Bought lingerie and wore it for sex",
    "Posted an explicit photo anonymously online",
  ],
  spicy2: [
    "Had rough sex",
    "Used restraints or cuffs",
    "Used a blindfold",
    "Did a full BDSM scene with a safeword",
    "Tried impact play with an implement",
    "Tried wax play",
    "Tried sensation play with multiple tools",
    "Tried roleplay with power dynamics",
    "Tried humiliation talk",
    "Tried praise kink",
    "Tried obedience and commands for a full session",
    "Tried orgasm denial",
    "Tried forced orgasm play",
    "Tried overstimulation play",
    "Tried mutual masturbation while making eye contact",
    "Tried filming a short private clip",
    "Tried taking a full nude set for your partner",
    "Tried anal play with fingers",
    "Tried anal play with a toy",
    "Had anal sex",
    "Tried pegging",
    "Tried a butt plug during sex",
    "Tried riding your partner's face",
    "Had a threesome",
    "Went to a sex shop together",
    "Tried cum play",
    "Tried lingerie plus heels for sex",
    "Tried a 'no touching' tease phase before sex",
    "Tried a rule-based session with punishments you agreed on",
    "Full night focused only on your partner's pleasure",
    "Tried switching who is dominant mid-session",
    "Tried a new kink",
    "Had sex after a planned tease day of sexting",
    "Posted explicit photos anonymously online and interacted with comments",
  ],
  spicy3: [
    "Did a dominant and submissive scene",
    "Tried rope bondage",
    "Tried stronger impact play",
    "Tried a longer endurance session focused on control",
    "Tried service submission for a full evening",
    "Tried a full roleplay with costumes and a script",
    "Tried consensual non-consent roleplay with strict boundaries",
    "Tried a restraint setup that limits movement significantly",
    "Tried sensory deprivation with multiple elements",
    "Tried orgasm torture play",
    "Tried extended edging for a full session",
    "Tried a toy-only orgasm challenge",
    "Tried multiple orgasms back-to-back",
    "Tried a dominant-led session where the submissive cannot speak",
    "Tried a humiliation scene",
    "Tried objectification talk",
    "Tried a fear-play flavored scene using only words and roleplay",
    "Tried a high-intensity role reversal session",
    "Tried a partner-sharing",
    "Had group sex",
    "Tried a kink-focused getaway weekend",
    "Tried recording a private video",
    "Tried a photo and video session",
    "Tried advanced toy play with multiple toys in one session",
    "Tried double penetration with toys",
    "Tried fisting",
    "Tried a scene focused on pain and pleasure balance",
    "Posted explicit content anonymously online and engaged in requests/roleplay",
  ],
  travel: [
    "Visited a new country",
    "Took a solo trip",
    "Stayed in an Airbnb",
    "Tried local street food",
    "Went backpacking",
    "Visited a UNESCO World Heritage site",
    "Took a road trip",
    "Stayed in a hostel",
    "Tried a new mode of transportation",
    "Visited a famous landmark",
    "Went island hopping",
    "Tried a new language (basic phrases)",
    "Visited a national park",
    "Took a train journey",
    "Stayed in a treehouse or unique accommodation",
    "Visited a desert",
    "Went to a music festival abroad",
    "Tried a traditional local activity",
    "Visited a mountain range",
    "Took a cruise",
    "Stayed in a beach resort",
    "Visited a historical site",
    "Went on a safari",
    "Tried a new cuisine in its origin country",
    "Visited a tropical destination",
    "Took a photography tour",
    "Stayed in a capsule hotel",
    "Visited a famous museum abroad",
    "Went to a local market in a foreign country",
    "Tried a new water sport",
    "Visited a volcano",
    "Took a cooking class abroad",
    "Stayed in a castle or palace",
    "Visited a famous beach",
    "Went to a cultural festival",
    "Tried a new adventure activity",
    "Visited a famous city",
    "Took a wine or food tour",
    "Stayed in a glamping site",
    "Visited a famous temple or church",
  ],
  fitness: [
    "Ran a 5K",
    "Completed a 30-day fitness challenge",
    "Lifted weights for the first time",
    "Tried CrossFit",
    "Completed a yoga class",
    "Went for a 10-mile bike ride",
    "Swam laps for 30 minutes",
    "Completed a HIIT workout",
    "Tried Pilates",
    "Went rock climbing",
    "Completed a marathon",
    "Tried boxing or kickboxing",
    "Went for a 5-mile hike",
    "Completed a spin class",
    "Tried barre",
    "Went for a morning run",
    "Completed a strength training program",
    "Tried martial arts",
    "Went for a long walk (5+ miles)",
    "Completed a bootcamp class",
    "Tried aerial yoga",
    "Went for a swim in open water",
    "Completed a running program",
    "Tried dance fitness",
    "Went for a trail run",
    "Completed a flexibility program",
    "Tried water aerobics",
    "Went for a bike ride (20+ miles)",
    "Completed a bodyweight workout",
    "Tried TRX training",
    "Went for a power walk",
    "Completed a cardio session (45+ min)",
    "Tried functional fitness",
    "Went for a jog in the rain",
    "Completed a stretching routine",
    "Tried resistance band training",
    "Went for a sunrise workout",
    "Completed a full body workout",
    "Tried kettlebell training",
    "Went for a sunset workout",
  ],
  creativity: [
    "Painted a canvas",
    "Wrote a short story",
    "Took a photography class",
    "Created a piece of pottery",
    "Wrote a poem",
    "Drew a portrait",
    "Created a digital art piece",
    "Wrote a song",
    "Made a sculpture",
    "Created a collage",
    "Wrote a blog post",
    "Took a drawing class",
    "Created a piece of jewelry",
    "Wrote a screenplay",
    "Made a short film",
    "Created a piece of calligraphy",
    "Wrote a novel chapter",
    "Took a painting class",
    "Created a piece of origami",
    "Wrote a play",
    "Made a music video",
    "Created a piece of embroidery",
    "Wrote a memoir chapter",
    "Took a pottery class",
    "Created a piece of woodwork",
    "Wrote a children's story",
    "Made a documentary",
    "Created a piece of textile art",
    "Wrote a personal essay",
    "Took a sculpture class",
    "Created a piece of mixed media art",
    "Wrote a haiku collection",
    "Made a stop-motion animation",
    "Created a piece of glass art",
    "Wrote a travelogue",
    "Took a photography workshop",
    "Created a piece of street art",
    "Wrote a journal entry",
    "Made a music composition",
    "Created a piece of performance art",
  ],
};

export const THEME_LABELS: Record<Theme, string> = {
  basic: "Basic",
  goals: "Goals",
  regrets: "Regrets",
  ideas: "Ideas",
  innovations: "Innovations",
  hobbies: "Hobbies",
  mindset: "Mindset",
  spicy: "Spicy",
  spicy2: "Spicy (Level 2)",
  spicy3: "Spicy (Level 3)",
  travel: "Travel",
  fitness: "Fitness",
  creativity: "Creativity",
};

// Themes that should be shown in the selector (excluding spicy2 and spicy3)
export const SELECTABLE_THEMES: Theme[] = [
  "basic",
  "goals",
  "regrets",
  "ideas",
  "innovations",
  "hobbies",
  "mindset",
  "spicy",
  "travel",
  "fitness",
  "creativity",
];
