export type Theme = "basic" | "goals" | "regrets" | "ideas" | "innovations" | "hobbies" | "mindset";

export const THEMED_ITEMS: Record<Theme, string[]> = {
  basic: [
    "Started a new hobby (and stuck with it 30 days)",
    'Deleted an app you "couldn\'t live without"',
    "Took a social media break for a week",
    "Read a book you actually finished",
    "Joined a club or recurring group",
    "Hosted a dinner or potluck",
    "Went to a museum or gallery",
    "Tried a new cuisine you'd never ordered before",
    "Learned a new recipe you'll reuse",
    "Cooked a meal entirely from pantry staples",
    "Packed lunch instead of buying it (5 times)",
    "Tried meal prep (even a lazy version)",
    "Made coffee at home for a month",
    'Did a "no spend" weekend',
    "Negotiated a bill or subscription",
    "Canceled a subscription you forgot about",
    "Hit a savings milestone (any size)",
    "Checked your credit report",
    "Updated your budget categories",
    'Sold something you\'ve been "meaning to list"',
    "Donated a box of stuff",
    "Decluttered one doom drawer",
    "Cleaned behind the fridge/stove (yes, really)",
    "Finally fixed the small annoying thing at home",
    "Changed an air filter",
    "Organized your cables / charging station",
    "Backed up your photos",
    "Cleaned up your email inbox (1,000+ gone)",
    "Unsubscribed from 25 email lists",
    "Went to bed before 10:30 for a week",
    "Took a proper sick day (rested, no guilt)",
    "Got a physical / annual checkup",
    "Scheduled the appointment you've avoided",
    "Walked 10k steps in a day",
    'Did a "stretching only" workout day',
    "Completed a 30-minute workout",
    "Tried yoga or mobility class",
    "Tried a new sport or activity",
    "Went hiking or to a nature trail",
    "Watched a sunrise",
    "Watched a sunset",
    "Took a day trip to a nearby town",
    "Booked a weekend getaway",
    "Traveled somewhere new (even one county over)",
    "Took a spontaneous drive with no destination",
    "Went to a farmers market",
    "Ate outside just because",
    "Took yourself on a solo date",
    "Went to a concert/show/comedy night",
    "Saw live music at a bar/park",
    "Went to a local festival",
    "Did karaoke",
    "Danced in public",
    "Started a conversation with a stranger",
    "Gave a genuine compliment to someone",
    "Wrote a thank-you note (handwritten)",
    "Reconnected with an old friend",
    "Made a new friend",
    "Set a boundary and kept it",
    'Said "no" without over-explaining',
    "Asked for help when you needed it",
    "Did something alone you usually wait for others to do",
    "Tried therapy/coaching/journaling regularly",
    "Journaled 7 days in a row",
    'Did a "brain dump" and made a plan',
    "Kept a promise to yourself",
    "Started a habit tracker",
    "Finished a project you've postponed",
    "Launched something (post, site, product, side project)",
    'Shipped a "v1" instead of perfecting forever',
    "Learned a new tool (spreadsheets, design, code, etc.)",
    "Automated something annoying in your life",
    "Cleaned up your desktop / file system",
    "Updated your passwords / enabled MFA",
    "Replaced something worn-out you keep tolerating",
    "Got rid of clothes that don't fit your life anymore",
    "Tried a new haircut or style",
    "Changed up your routine (new route, new gym time, etc.)",
    "Took a cold plunge / cold shower",
    "Did a sauna / steam room session",
    "Took a nap without setting an alarm",
    'Had a full "phone-free" morning',
    'Had a full "phone-free" evening',
    "Went a day without complaining",
    "Meditated for 10 minutes",
    "Took vitamins consistently for a month",
    "Drank enough water for 7 straight days",
    "Tried a mocktail night instead of drinking",
    "Went on a date night (planned)",
    "Went on a date night (spontaneous)",
    "Initiated intimacy you actually wanted",
    'Bought yourself flowers / a small treat "just because"',
    "Had a meaningful talk without distractions",
    'Made a "joy list" and did one thing from it',
    "Did a random act of kindness",
    "Volunteered for an hour",
    "Left a thoughtful review for a small business",
    'Asked someone "how can I support you this week?"',
    "Tried something that scared you a little (but was safe)",
    "Forgave yourself for something you've been carrying",
  ],
  goals: [
    "Run a 5K race",
    "Save $5,000 this year",
    "Read 24 books",
    "Learn a new language",
    "Get a promotion",
    "Start a side business",
    "Buy a house",
    "Travel to 3 new countries",
    "Complete a certification",
    "Run a marathon",
    "Write a book",
    "Start investing",
    "Get in the best shape of my life",
    "Master a new skill",
    "Build an emergency fund",
    "Start a YouTube channel",
    "Learn to play an instrument",
    "Complete a home renovation",
    "Start a garden",
    "Volunteer 100 hours",
    "Get a degree or certification",
    "Start a retirement fund",
    "Learn to cook 10 new dishes",
    "Complete a fitness challenge",
    "Start a blog",
    "Learn photography",
    "Get a new job",
    "Pay off all debt",
    "Start a podcast",
    "Learn to code",
    "Take a solo trip",
    "Start a daily meditation practice",
    "Complete a 30-day challenge",
    "Learn public speaking",
    "Start a book club",
    "Get a professional certification",
    "Start a savings goal tracker",
    "Learn graphic design",
    "Start a morning routine",
    "Complete a personal project",
  ],
  regrets: [
    "Didn't take that job opportunity",
    "Didn't travel when I had the chance",
    "Didn't call my parents more",
    "Didn't pursue that passion",
    "Didn't save money earlier",
    "Didn't take care of my health",
    "Didn't end that toxic relationship sooner",
    "Didn't learn that skill I wanted",
    "Didn't start that business idea",
    "Didn't say 'I love you' more often",
    "Didn't take more risks",
    "Didn't spend time with friends",
    "Didn't pursue higher education",
    "Didn't invest in myself",
    "Didn't travel solo",
    "Didn't learn to cook",
    "Didn't exercise regularly",
    "Didn't save for retirement",
    "Didn't take that class",
    "Didn't start that hobby",
    "Didn't network more",
    "Didn't ask for help",
    "Didn't set boundaries",
    "Didn't prioritize mental health",
    "Didn't learn financial literacy",
    "Didn't take breaks",
    "Didn't celebrate small wins",
    "Didn't document memories",
    "Didn't try new things",
    "Didn't be more present",
    "Didn't forgive sooner",
    "Didn't express gratitude",
    "Didn't take photos",
    "Didn't write in a journal",
    "Didn't learn from failures",
    "Didn't take that trip",
    "Didn't call that friend",
    "Didn't say yes to opportunities",
    "Didn't say no to things I didn't want",
    "Didn't trust my instincts",
  ],
  ideas: [
    "Start a community garden",
    "Create a local book exchange",
    "Organize neighborhood cleanups",
    "Start a skill-sharing group",
    "Create a meal prep service",
    "Start a walking group",
    "Organize a local market",
    "Create a mentorship program",
    "Start a repair cafe",
    "Organize a swap meet",
    "Create a time bank",
    "Start a tool library",
    "Organize a community event",
    "Create a local newsletter",
    "Start a makerspace",
    "Organize a study group",
    "Create a recipe exchange",
    "Start a carpool system",
    "Organize a clothing swap",
    "Create a local directory",
    "Start a podcast about local issues",
    "Organize a film screening",
    "Create a community art project",
    "Start a local history project",
    "Organize a talent show",
    "Create a neighborhood app",
    "Start a community kitchen",
    "Organize a game night",
    "Create a local guide",
    "Start a support group",
    "Organize a workshop series",
    "Create a resource library",
    "Start a community board",
    "Organize a festival",
    "Create a local blog",
    "Start a volunteer network",
    "Organize a fundraiser",
    "Create a mentorship matching",
    "Start a discussion group",
    "Organize a cultural exchange",
  ],
  innovations: [
    "AI-powered personal assistant",
    "Sustainable packaging solution",
    "Smart home automation system",
    "Renewable energy device",
    "Health monitoring wearable",
    "Educational app for kids",
    "Food waste reduction app",
    "Virtual reality training tool",
    "Blockchain voting system",
    "3D printing service platform",
    "Electric vehicle charging network",
    "Water purification device",
    "Mental health app",
    "Remote work collaboration tool",
    "Sustainable fashion platform",
    "Personal finance AI",
    "Language learning VR",
    "Smart agriculture system",
    "Accessibility tech solution",
    "Carbon footprint tracker",
    "Telemedicine platform",
    "Smart city infrastructure",
    "Recycling innovation",
    "Biometric security system",
    "Augmented reality shopping",
    "Personalized learning platform",
    "Smart transportation app",
    "Energy-efficient appliance",
    "Digital wellness tool",
    "Automated farming system",
    "Voice-controlled interface",
    "Gesture recognition tech",
    "Smart grid solution",
    "Biodegradable material",
    "Personalized medicine tool",
    "Automated delivery system",
    "Smart waste management",
    "Virtual event platform",
    "AI content creation tool",
    "Sustainable building material",
  ],
  hobbies: [
    "Photography",
    "Painting",
    "Drawing",
    "Sculpting",
    "Pottery",
    "Knitting",
    "Crocheting",
    "Sewing",
    "Woodworking",
    "Gardening",
    "Cooking",
    "Baking",
    "Reading",
    "Writing",
    "Journaling",
    "Calligraphy",
    "Origami",
    "Scrapbooking",
    "Collecting stamps",
    "Collecting coins",
    "Bird watching",
    "Hiking",
    "Camping",
    "Fishing",
    "Cycling",
    "Running",
    "Swimming",
    "Yoga",
    "Dancing",
    "Playing guitar",
    "Playing piano",
    "Singing",
    "Learning languages",
    "Chess",
    "Board games",
    "Video games",
    "Puzzles",
    "Sudoku",
    "Crosswords",
    "Model building",
    "RC cars/planes",
    "Astronomy",
    "Stargazing",
    "Geocaching",
    "Rock climbing",
    "Surfing",
    "Kayaking",
    "Skiing",
    "Snowboarding",
    "Martial arts",
    "Archery",
  ],
  mindset: [
    "Practice gratitude daily",
    "Embrace failure as learning",
    "Focus on progress not perfection",
    "Practice mindfulness",
    "Challenge negative thoughts",
    "Set boundaries",
    "Practice self-compassion",
    "Embrace uncertainty",
    "Focus on what I can control",
    "Practice patience",
    "Cultivate curiosity",
    "Embrace change",
    "Practice resilience",
    "Focus on solutions not problems",
    "Practice active listening",
    "Embrace vulnerability",
    "Practice forgiveness",
    "Focus on the present moment",
    "Practice acceptance",
    "Embrace imperfection",
    "Practice empathy",
    "Focus on growth mindset",
    "Practice self-reflection",
    "Embrace discomfort",
    "Practice intentional living",
    "Focus on values not validation",
    "Practice letting go",
    "Embrace new perspectives",
    "Practice balance",
    "Focus on process not outcome",
    "Practice authenticity",
    "Embrace the journey",
    "Practice kindness to self",
    "Focus on abundance mindset",
    "Practice emotional regulation",
    "Embrace challenges",
    "Practice positive self-talk",
    "Focus on learning mindset",
    "Practice being present",
    "Embrace uncertainty with courage",
  ],
};

export const THEME_LABELS: Record<Theme, string> = {
  basic: "Basic",
  goals: "Goals",
  regrets: "Regrets",
  ideas: "Ideas",
  innovations: "Innovations",
  hobbies: "Hobbies",
  mindset: "Mindset",
};

