export const BINGO_ITEMS_2026 = [
  "Started a new hobby (and stuck with it 30 days)",
  'Deleted an app you "couldn\'t live without"',
  "Took a social media break for a week",
  "Read a book you actually finished",
  "Joined a club or recurring group",
  "Hosted a dinner or potluck",
  "Went to a museum or gallery",
  "Tried a new cuisine you'd never ordered before",
  "Learned a new recipe you'll reuse",
  "Cooked a meal entirely from pantry staples",
  "Packed lunch instead of buying it (5 times)",
  "Tried meal prep (even a lazy version)",
  "Made coffee at home for a month",
  'Did a "no spend" weekend',
  "Negotiated a bill or subscription",
  "Canceled a subscription you forgot about",
  "Hit a savings milestone (any size)",
  "Checked your credit report",
  "Updated your budget categories",
  'Sold something you\'ve been "meaning to list"',
  "Donated a box of stuff",
  "Decluttered one doom drawer",
  "Cleaned behind the fridge/stove (yes, really)",
  "Finally fixed the small annoying thing at home",
  "Changed an air filter",
  "Organized your cables / charging station",
  "Backed up your photos",
  "Cleaned up your email inbox (1,000+ gone)",
  "Unsubscribed from 25 email lists",
  "Went to bed before 10:30 for a week",
  "Took a proper sick day (rested, no guilt)",
  "Got a physical / annual checkup",
  "Scheduled the appointment you've avoided",
  "Walked 10k steps in a day",
  'Did a "stretching only" workout day',
  "Completed a 30-minute workout",
  "Tried yoga or mobility class",
  "Tried a new sport or activity",
  "Went hiking or to a nature trail",
  "Watched a sunrise",
  "Watched a sunset",
  "Took a day trip to a nearby town",
  "Booked a weekend getaway",
  "Traveled somewhere new (even one county over)",
  "Took a spontaneous drive with no destination",
  "Went to a farmers market",
  "Ate outside just because",
  "Took yourself on a solo date",
  "Went to a concert/show/comedy night",
  "Saw live music at a bar/park",
  "Went to a local festival",
  "Did karaoke",
  "Danced in public",
  "Started a conversation with a stranger",
  "Gave a genuine compliment to someone",
  "Wrote a thank-you note (handwritten)",
  "Reconnected with an old friend",
  "Made a new friend",
  "Set a boundary and kept it",
  'Said "no" without over-explaining',
  "Asked for help when you needed it",
  "Did something alone you usually wait for others to do",
  "Tried therapy/coaching/journaling regularly",
  "Journaled 7 days in a row",
  'Did a "brain dump" and made a plan',
  "Kept a promise to yourself",
  "Started a habit tracker",
  "Finished a project you've postponed",
  "Launched something (post, site, product, side project)",
  'Shipped a "v1" instead of perfecting forever',
  "Learned a new tool (spreadsheets, design, code, etc.)",
  "Automated something annoying in your life",
  "Cleaned up your desktop / file system",
  "Updated your passwords / enabled MFA",
  "Replaced something worn-out you keep tolerating",
  "Got rid of clothes that don't fit your life anymore",
  "Tried a new haircut or style",
  "Changed up your routine (new route, new gym time, etc.)",
  "Took a cold plunge / cold shower",
  "Did a sauna / steam room session",
  "Took a nap without setting an alarm",
  'Had a full "phone-free" morning',
  'Had a full "phone-free" evening',
  "Went a day without complaining",
  "Meditated for 10 minutes",
  "Took vitamins consistently for a month",
  "Drank enough water for 7 straight days",
  "Tried a mocktail night instead of drinking",
  "Went on a date night (planned)",
  "Went on a date night (spontaneous)",
  "Initiated intimacy you actually wanted",
  'Bought yourself flowers / a small treat "just because"',
  "Had a meaningful talk without distractions",
  'Made a "joy list" and did one thing from it',
  "Did a random act of kindness",
  "Volunteered for an hour",
  "Left a thoughtful review for a small business",
  'Asked someone "how can I support you this week?"',
  "Tried something that scared you a little (but was safe)",
  "Forgave yourself for something you've been carrying",
];
